export interface TechnicianOption {
  codigo: string;
  nombre: string;
}

export const TECHNICIANS: TechnicianOption[] = [
  { codigo: '120', nombre: 'JUAN JOSE ALBINANA LLORIA' },
  { codigo: '379', nombre: 'NICUSOR ANDREI' },
  { codigo: '152', nombre: 'JOSE ANDRES CATALA' },
  { codigo: '241', nombre: 'SERGIO BELTRAN GONZALEZ' },
  { codigo: '165', nombre: 'ARGEMIRO BOTERO VALENCIA' },
  { codigo: '349', nombre: 'JOAQUIN BRAOJOS JIMENEZ' },
  { codigo: '395', nombre: 'CARLOS CABANES CARMONA' },
  { codigo: '439', nombre: 'JOSE FRANCISCO CALZADA SANCHEZ' },
  { codigo: '101', nombre: 'ANIBAL CARCEL AROCAS' },
  { codigo: '21', nombre: 'CASTILLA RODRIGUEZ IVAN' },
  { codigo: '441', nombre: 'JULIO COSTA MARTINEZ' },
  { codigo: '384', nombre: 'JOSE GREGORIO CRESPO MENDEZ' },
  { codigo: '189', nombre: 'ALBERTO DE LA CALLE GARCIA' },
  { codigo: '438', nombre: 'JESUS (MADRID) DEL PRADO ZAMORANO' },
  { codigo: '456', nombre: 'JAVIER FERNANDEZ BERNAD' },
  { codigo: '380', nombre: 'ALBERTO FERNANDEZ VICENTE' },
  { codigo: '401', nombre: 'JULIO TOMAS FORTEA CASAÑ' },
  { codigo: '414', nombre: 'ADRIAN GALDON SOLIVA' },
  { codigo: '442', nombre: 'ALEJANDRO GAMBORINO CATALAN' },
  { codigo: '270', nombre: 'JAVIER GARCIA LOPEZ' },
  { codigo: '443', nombre: 'DANIEL GARZON GARRIDO' },
  { codigo: '451', nombre: 'JORGE GIMENEZ FARIÑAS' },
  { codigo: '392', nombre: 'JOSE GONZALEZ BATALLER' },
  { codigo: '523', nombre: 'WILLIAM FERNANDO (ALICANTE) GUERRERO ROMAN' },
  { codigo: '509', nombre: 'FRANCISCO (MADRID) GUTIERREZ ROSA' },
  { codigo: '453', nombre: 'MANUEL GUTIERREZ VELASCO' },
  { codigo: '382', nombre: 'RITCHI LEROY ICHUSTE ANGELETTI' },
  { codigo: '376', nombre: 'BRIAN NICOLAS IOANNU' },
  { codigo: '447', nombre: 'DAVID (ALICANTE) JAEN PASTOR' },
  { codigo: '337', nombre: 'RODRIGO (MADRID) JODAR MOTA' },
  { codigo: '419', nombre: 'VLADIMIRO KLEMENCIC' },
  { codigo: '354', nombre: 'JUAN FRANCISCO LOPEZ IGEA' },
  { codigo: '450', nombre: 'DANIEL (ALICANTE) LUCAS PRIETO' },
  { codigo: '91', nombre: 'VICTOR MANUEL MARIN BAEZA' },
  { codigo: '486', nombre: 'JESUS (MADRID) MAROTO ROMERO' },
  { codigo: '487', nombre: 'JONATHAN DAVID MARTINEZ' },
  { codigo: '188', nombre: 'MIGUEL MARTINEZ FERRANDO' },
  { codigo: '333', nombre: 'IGNACIO MARTINEZ LEJARZA CAÑELLAS' },
  { codigo: '423', nombre: 'JOSE LUIS MATEU MOTA' },
  { codigo: '301', nombre: 'JAIRO MENA ILLESCAS' },
  { codigo: '397', nombre: 'ANDRES MERLOS BLANCA' },
  { codigo: '405', nombre: 'MOHAMED MEZIANI' },
  { codigo: '326', nombre: 'JOSE MIGUEL MOLINA SOTO' },
  { codigo: '511', nombre: 'MIGUEL ANDRES MUJICA JIMENEZ' },
  { codigo: '454', nombre: 'JAVIER MULLOR GARCIA' },
  { codigo: '488', nombre: 'JOSE LUIS NIEVA FENOLL' },
  { codigo: '518', nombre: 'MAURICIO OCHOA JIMENEZ' },
  { codigo: '65', nombre: 'MARIANO OLIVER GONZALEZ' },
  { codigo: '322', nombre: 'MAURICIO PAEZ' },
  { codigo: '520', nombre: 'DAVID PASCUAL MARTINEZ' },
  { codigo: '302', nombre: 'ALVARO PEREZ ELEUTERIO' },
  { codigo: '87', nombre: 'ANTONIO MANUEL PROSPER DE LA FUENTE' },
  { codigo: '383', nombre: 'EDUARD ANDRES RODRIGUEZ GERVAZZI' },
  { codigo: '410', nombre: 'MARTIN ADRIAN RODRIGUEZ PAZ' },
  { codigo: '356', nombre: 'ISRAEL RUBIO BARCIA' },
  { codigo: '142', nombre: 'FRANCISCO ANGEL SAEZ ABAD' },
  { codigo: '353', nombre: 'MOHAMED (ALICANTE) SAHRAOUI' },
  { codigo: '173', nombre: 'JULIAN SALCEDO ANDRADE' },
  { codigo: '449', nombre: 'DIEGO PATRICIO (ALICANTE) SOSA' },
  { codigo: '381', nombre: 'JOSE MIGUEL VALVERDE GIL' },
  { codigo: '94', nombre: 'DAVID VAÑO GARCIA' },
  { codigo: '366', nombre: 'VOINESCU ANDREI' },
  { codigo: '362', nombre: 'CRISTIAN VOINESCU' },
  { codigo: '421', nombre: 'MATIAS ANDRES ZANETTI FONTAINE' }
];
